### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by alexnaidovich** [Pavel-Yarakhovich/Glassy#3]
**Type**: bug

**Steps to reproduce**:
  * downolad project
  * run `npm install`
  * run `npm start`

**Expected behavior**:
project is compiled and is displayed properly at `http://localhost:3000/`

**Actual behavior**:
compilation error is thrown to `http://localhost:3000/`

```
Failed to compile

./src/hoc/Layout/Layout.js
  Line 10:  React Hook "useState" is called in function "layout" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

Search for the keywords to learn more about each error.
```

**Comment by Pavel-Yarakhovich** [comment]
The 'Glassy' project is neither a React app nor contains any HOCs.

**Comment by alexnaidovich** [comment]
@Pavel-Yarakhovich I'm sorry, I've posted it at the wrong place. I faced this issue with your "Lemon" project. You may close this issue.
